# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Interface:
    def setup_ui(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(680, 230)
        MainWindow.setStyleSheet("QLineEdit {\n"
"    border-radius: 10px;\n"
"    padding-left: 3px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    border-radius: 20px;\n"
"    background: rgb(84, 84, 84);\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    background: rgb(115, 115, 115);\n"
"}\n"
"\n"
"QPushButton::pressed {\n"
"    background: rgb(161, 161, 161);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.password = QtWidgets.QLineEdit(self.centralwidget)
        self.password.setGeometry(QtCore.QRect(10, 50, 650, 30))
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")
        self.name = QtWidgets.QLineEdit(self.centralwidget)
        self.name.setGeometry(QtCore.QRect(10, 10, 650, 30))
        self.name.setObjectName("name")
        self.login = QtWidgets.QPushButton(self.centralwidget)
        self.login.setGeometry(QtCore.QRect(10, 111, 660, 50))
        self.login.setObjectName("login")
        self.register = QtWidgets.QPushButton(self.centralwidget)
        self.register.setGeometry(QtCore.QRect(10, 171, 660, 50))
        self.register.setObjectName("register_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Вход или регистрация"))
        self.password.setPlaceholderText(_translate("MainWindow", "Пароль"))
        self.name.setPlaceholderText(_translate("MainWindow", "Имя"))
        self.login.setText(_translate("MainWindow", "Войти"))
        self.register.setText(_translate("MainWindow", "Зарегистрироваться"))
